config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  default_url_options :host => ENV['HOST']
  devise_for :users, controllers: { 
    registrations: 'users/registrations', 
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  patch 'task/change_status', action: :change_status, controller: 'task'
  get 'schedule', to: 'schedule#index'
  get 'kanban', to: 'task#kanban'

  # patch "task/change_status" , to:"tasks#change_status"
  
  resources :role
  resources :users do
    collection do
      post 'create_user'
      patch 'change_image'
    end
  end

  resources :issues do 
    collection do 
      get 'assign_issue_show'
      patch 'assign_issue'
      get 'my_issue'
    end
  end
  resources :tags   do 
     
  end
  resources :projects do

    resources :sprint do
      resources :task do
        collection do 
          get "kanban"
        end
      end
      collection do
        
      end
    end
    
    resources :task do
      collection do 
        get "kanban"
      end
    end
    collection do

      patch "save_review_rating"
      get "project_status"
      get "review_rating"
     
    end
  end

  
  resources :admin do
    collection do
      get 'soft_delete'
      get "alluser"
    end
  end
 
  root "home#index"
  get 'employee', to: 'home#employee'
  
end

app/models/issue.rb
# frozen_string_literal: true

class Issue < ApplicationRecord
  acts_as_paranoid
  belongs_to :project, class_name: 'Project'
  belongs_to :creator, class_name: 'User'
  belongs_to :employee, class_name: 'User', optional: true
  has_many :tags ,:as => :label 
end

app/controllers/issues_controller.rb
# frozen_string_literal: true

class IssuesController < ApplicationController
  before_action :set_issue, only: %i[show edit update destroy]
  before_action :checking_authenticity_assign, only: %i[assign_issue_show]

  @@status = [['Created'], ['On Going'], ['Submitted'], ['Re-Submitted'], ['Rejected'], ['Done']]
  @@type = [['Bug'], ['Error']]

  # GET /issues or /issues.json
  def index
    @project_id = params[:format]

    @issues = Issue.where(project_id: @project_id).all
  end

  # GET /issues/1 or /issues/1.json
  def show
    checking_authenticity(@issue, :show)
    @status = @@status
    @type = @@type
  end

  # GET /issues/new
  def new
    @status = @@status
    @type = @@type
    @employee = []
    User.joins(:roles).where(roles: { name: 'employee' }).select(:id, :name).each { |v| @employee << [v.name, v.id] }

    project_id = params[:format]

    @issue = Issue.new
    @issue.project_id = project_id
  end

  # GET /issues/1/edit
  def edit
    checking_authenticity(@issue, :edit)
    @employee = []
    User.joins(:roles).where(roles: { name: 'employee' }).select(:id, :name).each { |v| @employee << [v.name, v.id] }
    @status = @@status
    @type = @@type
    p @issue
  end

  # POST /issues or /issues.json
  def create
    checking_authenticity(Issue.new, :create)

    @employee = []
    User.joins(:roles).where(roles: { name: 'employee' }).select(:id, :name).each { |v| @employee << [v.name, v.id] }

    @status = @@status
    @type = @@type
    temp = issue_params
    temp['status'] = 'Created'

    @issue = Issue.new(temp)
    @issue.creator_id = current_user.id

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issue_url(@issue), notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1 or /issues/1.json
  def update
    checking_authenticity(@issue, :update)
    @status = @@status
    @type = @@type
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to issue_url(@issue), notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    checking_authenticity(@issue, :destroy)
    @project = @issue.project
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url(@project), notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def assign_issue_show
    issue_id = params[:format]
    @issue = Issue.find(issue_id)
    @employee = []
    params[:status_id] = @issue.status
    @status = @@status
    User.joins(:roles).where(roles: { name: 'employee' }).select(:id, :name).each { |v| @employee << [v.name, v.id] }
    params[:selected_value] = @issue.employee_id unless @issue.employee_id.nil?
  end

  def assign_issue
    @issue = Issue.find(params[:id])
    @issue['status'] = params['issue']['status']
    @issue['employee_id'] =
      !params['issue']['employee_id'].nil? ? params['issue']['employee_id'] : @issue['employee_id']

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issue_url(@issue), notice: '' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def my_issue
    @project_id = params[:format]
    current_user_id = current_user.id

    @issues = Issue.where(employee_id: current_user_id, project_id: @project_id).all
  end

  private

  def checking_authenticity(issue, opration)
    render file: 'public/403.html' unless can? opration, issue
  end

  def checking_authenticity_assign
    @issue = Issue.find(params[:format])
    @project = Project.find(@issue.project_id)
    if current_user.roles.first.name == 'manager'

      render file: 'public/403.html' unless can? :assign_issue, @project
    else
      render file: 'public/403.html' unless can? :assign_issue, @issue

    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_issue
    @issue = Issue.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def issue_params
    params.require(:issue).permit(:project_id, :title, :description, :issue_type, :status)
  end
end

app/views/issues/_form.html.erb
<div  style="width: 500px; padding-top: 50px;" >
<%= form_with model: @issue  do |form| %>
  <% if issue.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-12">
    <%# <%= form.label :project_id, style: "display: block" %> 
    <%= form.hidden_field :project_id %>
  </div>

  <div class="col-md-12">
    <%= form.label :title, :class=>"form-label" %>
    <%= form.text_field :title,{ :class => 'form-control' } %>
  </div>

  <div class="col-md-12">
    <%= form.label :description, :class=>"form-label"%>
    <%= form.text_area :description ,  { :class => 'form-control' }%>
  </div>



  <div class="row">

    

    <div class="col-md-6">
       <%= form.label :issue_type, :class=>"form-label" %>
       <%# <%= form.select :type ,["Bug","Error"]  %%>
       <%= form.select(:issue_type,@type, {selected: params[:issue_type_id]}, { :class => 'form-control' }) %>
    </div>
  </div> 
 


  <div class="col-md-4 my-4">
   
    <%= form.submit :class=>"btn btn-primary"%>
  </div>
<% end %>
</div>

app/views/issues/_issue.html.erb
    <div class="container">

       
<div class="card" style="width: auto;  border-radius: 25px;">
  <div class="card-body " style="background-color: #b4b4b4 ; border-radius: 25px;">

                  <div id="<%= dom_id issue %>">
                    
                  <h2 class="card-title">
                    <p>
                      <%= issue.title.capitalize %>
                    </p>
                    </h2>
                      <p>
                      <strong>Project :</strong>
                      <%=Project.find_by(id:issue.project_id).name.capitalize %>
                    </p>
                    <p class="text-muted description" data-toggle="tooltip" data-placement="bottom" title="<%=issue.description%>">
                      <strong class="text-dark">Description:</strong>
                      <%=issue.description%>
                    </p>

                    

                    <p>
                      <strong>Type:</strong>
                      <% if (issue.issue_type=="Bug") %>
                      <span class="badge badge-pill badge-warning">Bug</span>
                      <% elsif (issue.issue_type=="Error") %>
                      <span class="badge badge-pill badge-danger">Error</span>
                      <%else%>
                        <span class="badge badge-pill badge-info">issue.issue_type</span>
                      
                      <%end%>
                    </p>

                    <p>
                      <strong>Status:</strong>
                      <%= issue.status %>
                    </p>

                    <p>
                      <strong>Employee:</strong>
                      <%if issue.employee_id==nil%>
                      <span style="color:red">Not Assign</span>
                      <%else%>
                      <span style="color:green">
                      <%= User.find_by(id:issue.employee_id).name %></span>
                      <%end%>
                      
                    </p>

                  </div>
    
    
  </div>
</div>
    
</div>

app/views/issues/assign_issue_show.html.erb
<div class="container ",style="margin: auto, width:700px">
<%= form_with model: @issue ,:url => {:action => :assign_issue,:id=>@issue.id} do |form| %>
<div class="col-md-6 py-1">  
      <%= form.label :status, :class=>"form-label py-1" %>
      <%= form.select(:status,@status , {selected: params[:status_id]}, { :class => 'form-control py-1' }) %>
    </div>
    <% unless current_user.has_role? "employee"%>

    <div class="col-md-12 py-1">
    <%= form.label :employee, :class=>"form-label " %>
    <%= form.select :employee_id, @employee, :selected => params[:selected_value], :class=>'form-control bg-primary' %>
<%end%>
  </div>
  <div class="col-md-4">
    <%= form.submit%>
  </div>
<%end%>
</div>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render "form", issue: @issue %>

<br>

<div >
  <%= link_to "Show this issue", @issue  , :class => 'btn btn-primary'%>
  <%= link_to "Back to issues", issues_path , :class => 'btn btn-primary'%>
</div>

app/views/issues/index.html.erb
<div class="container">
<%= link_to "New issue", new_issue_path(@project_id) ,:class => "btn btn-primary my-4"%>
<h3>All Issues</h3>

<div id="issues">
  <% @issues.each do |issue| %>
    <%= render issue %>
    <p style="padding-left: 50px; padding-top: 10px">
      <%= link_to "Show this issue", issue , :class => "btn btn-primary" %>
      <%= link_to "Assign this issue", assign_issue_show_issues_path(issue),:class => "btn btn-primary" %>
   
    </p>
  <% end %>
</div>
</div>

app/views/issues/my_issue.html.erb
<div class="container">
<%= link_to "New issue", new_issue_path(@project_id),:class => "btn btn-primary m-2" %>
<h1>My Issues</h1>

<div id="issues">
  <% @issues.each do |issue| %>
    <%= render issue %>
    <p>
      <%= link_to "Show this issue", issue %>
      |<%= link_to "Change status", assign_issue_show_issues_path(issue) %>
      
      
    </p>
  <% end %>
</div>
</div>

app/views/issues/new.html.erb
<div class="container"  style="width: 500px; padding-top: 50px;" >
<h1>New issue</h1>

<%= render "form", issue: @issue %>

<br>

<div>
  <%= link_to "Back to issues", issues_path %>
</div>
</div>

app/views/issues/show.html.erb
<%= render @issue %>
<div class="container">
<div>
  <%= link_to "Edit this issue", edit_issue_path(@issue),:class => "btn btn-primary m-2" %> 
  <%= link_to "Back to Projects", projects_path ,:class => "btn btn-primary m-2"%>
  <%= link_to "Assign this issue", assign_issue_show_issues_path(@issue) ,:class => "btn btn-primary m-2"%>
  <%= button_to "Destroy this issue", @issue, method: :delete ,:class => "btn btn-danger m-2"%>
</div>
</div>