config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  default_url_options :host => ENV['HOST']
  devise_for :users, controllers: { 
    registrations: 'users/registrations', 
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  patch 'task/change_status', action: :change_status, controller: 'task'
  get 'schedule', to: 'schedule#index'
  get 'kanban', to: 'task#kanban'

  # patch "task/change_status" , to:"tasks#change_status"
  
  resources :role
  resources :users do
    collection do
      post 'create_user'
      patch 'change_image'
    end
  end

  resources :issues do 
    collection do 
      get 'assign_issue_show'
      patch 'assign_issue'
      get 'my_issue'
    end
  end
  resources :tags   do 
     
  end
  resources :projects do

    resources :sprint do
      resources :task do
        collection do 
          get "kanban"
        end
      end
      collection do
        
      end
    end
    
    resources :task do
      collection do 
        get "kanban"
      end
    end
    collection do

      patch "save_review_rating"
      get "project_status"
      get "review_rating"
     
    end
  end

  
  resources :admin do
    collection do
      get 'soft_delete'
      get "alluser"
    end
  end
 
  root "home#index"
  get 'employee', to: 'home#employee'
  
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  acts_as_paranoid
  belongs_to :sprint, class_name: 'Sprint'
  belongs_to :user, class_name: 'User'
  has_many :hours, class_name: 'Hour', dependent: :delete_all
  validates :title, :sprint_id, :user_id, :due_date, :status, :description, presence: true
  validates_each :due_date do |records, attrs, value|
    records.errors.add(attrs, 'Must after todays date') unless value > Time.now
  end
  after_save do |task|
    case task['status']
    when 'On Going'
      hours_creat = Hour.find_by(task_id: task['id'])
      if !hours_creat.nil?
        hours_creat.ending = nil
      else
        hours_creat = Hour.new
        hours_creat.starting = Time.now
        hours_creat.task = task
      end
      hours_creat.save!

    when 'Done'

      hours_creat = Hour.find_by(task_id: task['id'])

      unless hours_creat.nil?
        hours_creat.ending = Time.now
        hours_creat.save!
      end
    end
  end

  filterrific(
    default_filter_params: { task_sorted_by: 'name_asc' },
    available_filters: [
      :task_sorted_by,
      :task_search_query,
      :with_task_status
    ]
  )

  scope :task_search_query, ->(query) {
    return nil  if query.blank?
    Task.where('lower(tasks.description) LIKE :search OR lower(tasks.title) LIKE :search', search: "%#{query.downcase}%")
  }

  scope :with_task_status, ->(status) {
    sprint_id = Task.where("tasks.status != 'Done'").select("tasks.sprint_id").map(&:sprint_id).uniq
    case status
      when /^overdue/
        where("tasks.due_date <  '#{Time.now}'")
      when status
        where(status: status)
      else
        raise(ArgumentError, "Invalid status option: #{status.inspect}")
      end
  }


  scope :task_sorted_by, ->(sort_option) {
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    tasks = Task.arel_table
    case sort_option.to_s
      when /^name_/
        order(tasks[:title].send(direction))
      when /^created_at_/
        order(tasks[:created_at].send(direction))
      when /^due_date/
        order(tasks[:due_date].send(direction))
      when /^updated_at_/
        order(tasks[:updated_at].send(direction))
      else
        raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Task start date', 'created_at_asc'],
      ['Task End date', 'due_date'],
      ['Last Modified', 'updated_at_desc']
    ]
  end

  def self.options_for_with_status
    [
      ['Done', 'Done'],
      ['On Going', 'On Going'],
      ['Created', 'Created'],
      ['Submitted','Submitted'],
      ['Re-Submitted','Re-Submitted'],
      ['Rejected','Rejected'],
      ['Over Due', 'overdue']
    ]
  end

  private

  def check_date
    due_date > Time.now
  end
end

app/controllers/task_controller.rb
# frozen_string_literal: true

class TaskController < ApplicationController
  before_action :set_project, except: %i[change_status kanban]

  before_action :set_task, only: %i[edit show]
  @@status = [['Created'], ['On Going'], ['Submitted'], ['Re-Submitted'], ['Rejected'], ['Done']]
  before_action :checking_authenticity_show, only: %i[show index]
  before_action :checking_authenticity_edit, only: %i[edit]
  before_action :checking_authenticity_new, only: %i[new create]
  def index
    @filterrific = initialize_filterrific(
      Task,
      params[:filterrific],
      select_options: {
        task_sorted_by: Task.options_for_sorted_by,
        with_task_status: Task.options_for_with_status,
      },
      persistence_id: "shared_key",
      default_filter_params: {},
      available_filters: [:task_sorted_by, :with_task_status, :task_search_query],
      sanitize_params: true,
    ) || return
    @status = @@status
    @tasks = if params.key?(:sprint_id)
                @filterrific.find.page(params[:page]).where(sprint_id: params[:sprint_id]).order(created_at: :asc)
             else
                @filterrific.find.page(params[:page]).joins(:sprint).where(sprint: { project_id: params[:project_id] }).order(created_at: :asc)
             end
    @hours = {}
    @tasks.each do |x|
      task_h = Hour.find_by(task_id: x.id)
      @hours[x.id] = if task_h.nil?
                       'Not Started'
                     elsif task_h.ending.nil?
                       'On Going'
                     else
                       ((task_h.ending - task_h.starting) / 1.hour).round(2)
                     end
    end
    # sql="SELECT * FROM #{@tasks} LEFT JOIN Hour ON @tasks.id=Hour.task_id;"
    # p @tasks.left_outer_joins(:hours).select("@tasks.id,hours.starting")
    # p execute_statement(sql)
  end

  def kanban
    render file: 'public/403.html' if current_user.has_role? "customer"
    @status = @@status
    @tasks = if params.key?(:project_id)
               if params.key?(:sprint_id)
                 Task.where(sprint_id: params[:sprint_id]).order(created_at: :asc)
               else
                 Task.joins(:sprint).where(sprint: { project_id: params[:project_id] }).order(created_at: :asc)
               end
             else
               Task.all
             end
    @hours = {}
    @tasks.each do |x|
      task_h = Hour.find_by(task_id: x.id)
      @hours[x.id] = if task_h.nil?
                       'Not Started'
                     elsif task_h.ending.nil?
                       'On Going'
                     else
                       ((task_h.ending - task_h.starting) / 1.hour).round(2)
                     end
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
    @employees = getEmployee
    @sprints = getSprint
    @status = @@status
  end

  def create
    flag = params.key?(:sprint_id)
    @task = Task.new(task_params)
    params[:sprint_id] = @task.sprint.id
    params[:employee_id] = @task.user_id
    @employees = getEmployee
    @sprints = getSprint
    @status = @@status
    respond_to do |format|
      if @task.save
        format.html do

        add_flash_message('notice', 'Task was successfully created.')
          if flag
            redirect_to project_sprint_task_index_path
          else
            redirect_to project_task_index_path
          end
        end
      else
        add_flash_message('warning', 'Task is not created please try again.')
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    # checking_authenticity_edit(:edit)
    @task = Task.find(params[:id])
    @employees = getEmployee
    @sprints = getSprint
    params[:sprint_id] = @task.sprint.id
    params[:employee_id] = @task.user_id
    params[:status_id] = @task.status
    @status = @@status
  end

  def update
    # checking_authenticity_edit(:update)
    @task = Task.find(params[:id])

    params[:sprint_id] = @task.sprint.id
    params[:employee_id] = @task.user_id
    params[:status_id] = @task.status
    @employees = getEmployee
    @sprints = getSprint
    @status = @@status
    project_id = params[:project_id]
    p @task
    respond_to do |format|
      if @task.update(task_params)
        # redirect_to (project_task_index_path)
        # return
        format.html do
          add_flash_message('notice', 'Task was successfully updated.')
          if params.key?(:sprint_id)
            redirect_to project_sprint_task_index_path(project_id: project_id, sprint_id: params[:sprint_id])
          else
            redirect_to project_task_index_path(project_id: project_id)
          end
        end
        format.js
      else
        format.html do
          if params.key?(:sprint_id)
            render :project_sprint_task_index_path, status: :unprocessable_entity
          else
            render :project_task_index_path, status: :unprocessable_entity
          end
        end
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @project = @task.sprint.project
    if !(can? :destroy, @task)
      render file: 'public/403.html'
    elsif @task.destroy
      flash[:notice] = 'Task is deleted'
      add_flash_message('notice', 'Task was  deleted')
          
      render json: { respons_message: 'Task is deleted' }
    
      
    else
      add_flash_message('error', 'Something went wrong please try again.')
      format.html { render :new, status: :unprocessable_entity }
    end
  end

  # this method for AJAX call.it is use for status update
  def change_status
    json = JSON.parse request.body.read
    task = Task.find_by(id: json['id'])
    task.status = json['status']

    task.save!
    task_h = Hour.find_by(task_id: json['id'])

    # change hours variable calculate hours spend in task

    respons_message = if task_h.nil?
                        'Not Started'
                      elsif task_h.ending.nil?
                        'On Going'
                      else
                        ((task_h.ending - task_h.starting) / 1.hour).round(2)
                      end
  add_flash_message('notice', "Task status is changed to<b> #{json['status']}</b>.")
  helpers.flash_messages()
  
  # ApplicationHelper.flash_messages()
    render json: { respons_message: respons_message }
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :sprint_id, :user_id, :due_date, :status, :description)
  end

  def getEmployee(employees = [])
    User.joins(:roles).where(roles: { name: 'employee' }, delete_user: false).select(:id, :name).each do |employee|
      employees << [employee.name, employee.id]
    end
    employees
  end

  def getSprint(sprints = [])
    Sprint.all.where(project_id: params[:project_id]).each { |sprint| sprints << [sprint.title, sprint.id] }
    sprints
  end

  def checking_authenticity_show
    render file: 'public/403.html' unless can? :show, @project
  end

  def checking_authenticity_edit
    render file: 'public/403.html' unless can? :edit, @task
  end

  def checking_authenticity_new
    render file: 'public/403.html' unless can? :edit, @project
  end

  # this fot exicuting sql
  def execute_statement(sql)
    results = ActiveRecord::Base.connection.execute(sql)

    results if results.present?
  end
end

app/helpers/task_helper.rb
# frozen_string_literal: true

module TaskHelper
end

app/views/task/_form.html.erb
<%= form_with model: @task,:url => {:action => place},:html => {:class => 'row g-3 my-1'}  do |form| %>
<% unless current_user.has_role? "employee"%>
<div class="col-md-12">
    <%= form.label :title, :class=>"form-label" %><br>
    <%= form.text_field :title, :class=> "form-control" %>
</div>

    <div class="col-md-12">
    <%= form.label :Sprint,:class=>"form-label" %> <br>
    <%= form.select(:sprint_id,@sprints , {selected: params[:sprint_id]}, { :class => 'form-control' }) %>
</div>

<div class="col-md-12">
    <%= form.label :Employee,:class=>"form-label" %> <br>
    <%= form.select(:user_id,@employees , {selected: params[:employee_id]}, { :class => 'form-control' }) %>
</div>



<div class="col-md-12">
    <%= form.label "Due Date", style: "display: block" %>
    <%= form.date_select :due_date, :class => 'form-control' %>
</div>
<div class="col-md-12">
    <%= form.label :description %>
    <%= form.text_area :description, :class => 'form-control'%>
</div>
<% end%>
<div class="col-md-12">
    <%= form.label :Status,:class=>"form-label" %> <br>
    <%= form.select(:status,@status , {selected: params[:status_id]}, { :class => 'form-control' }) %>
</div>


<div class="col-12">
    <%= form.submit place,:class=>"btn btn-primary m-2" %>
</div>

<% end %>
      

app/views/task/_task.html.erb
<div class="container">
<div class="card" style="width: auto;  border-radius: 25px;">
  <div class="card-body " style="background-color: #b4b4b4 ; border-radius: 25px;">
<div>
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

</div>
</div>
</div>
</div>

app/views/task/edit.html.erb
<div class="container"  style="width: 30%; padding-top: 50px;" >
        <% if @task.errors.any? %>
        <div style="color: red">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
            <% @task.errors.each do |error| %>
            <li><%= error.full_message %></li>
                <% end %>
            </ul>
            </div>
        <% end %>

        <div class="col-md-12 pb-4">
            <h4>Update Task</h4>
        </div>

    <%= render "form", task: @task, place: :update %>         
</div>

      

app/views/task/index.html.erb
<div class="container">
<h1>Tasks</h1>
<div>
<%= link_to "Add New Task", new_project_task_path,class: "btn btn-primary" if ((can? :new, Task) && !(params.has_key?(:sprint_id))) %>
<%= link_to "Add New Task", new_project_sprint_task_path,class: "btn btn-primary" if ((can? :new, Task) && (params.has_key?(:sprint_id)))%>
<%= link_to "View Kanban", kanban_project_task_index_path,class: "btn btn-primary" if (!(current_user.has_role? "customer") && !(params.has_key?(:sprint_id))) %>
<%= link_to "View Kanban", kanban_project_sprint_task_index_path,class: "btn btn-primary" if (!(current_user.has_role? "customer") && (params.has_key?(:sprint_id)))%>
</div>
<div>
<%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit', class:"form-inline mt-3" } do |f| %>
        <div class= "d-flex align-items-center justify-content-around">
            <div>
              <%= f.text_field(
                :task_search_query,
                class: 'filterrific-periodically-observed form-control',
                placeholder: "Search"
              ) %>
              <%= f.select(
                :with_task_status, 
                @filterrific.select_options[:with_task_status],
                { include_blank: '- Status -'},
                {class:"form-control"}
              ) %>
              <%= f.select(
                :task_sorted_by, 
                @filterrific.select_options[:task_sorted_by], 
                { include_blank: '- Sorted By -' },
                {class:"form-control"}
                ) %>
              <%= f.submit 'Filter', class: "btn btn-primary" %>
              <%= link_to(
                'Reset filters',
                reset_filterrific_url,
                :class=>"btn btn-secondary"
              ) %>
          </div>
        </div>
        <%# add an automated spinner to your form when the list is refreshed %>
        <%# render_filterrific_spinner %>
      <% end %> 
</div>
<br><br>
<table class="table  table-striped table-hover table-bordered border-primary" style="text-align: center;" frame="VOID" rules="ALL">
  <thead  class="bg-info table-info">
    <th>Task Name</th>
    <th>Description</th>
    <th>Employee Name</th>
    <th>Employee Email</th>
    <th>status</th>
    
    <th> Action </th>

    <th> Hours </th>
    
  </thead>
  <tbody class="table-info">
  <% @tasks.each do |task| 
        employee = User.find(task.user_id)
  %>
  <tr d="column_<%= task.id%>">
    <td scope="row">
      <%= task.title %>
      <%
        # params[:project_id] = task.sprint.project_id
        params[:task] = task.id
      %>
    </td >
     <td scope="row">
      <%= task.description %>
    </td>
    <td scope="row">
      <%= employee.name%>
    </td>
    <td scope="row">
      <%= employee.email %>
    </td>
    <td scope="row">
    <% if can? :edit, task%>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="changeStatusDropDown_<%= task.id%>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= task.status%>
        </button>
        <div class="dropdown-menu" aria-labelledby="changeStatusDropDown_<%= task.id%>">
          <% @status.each do |status| %>
            <%=  link_to(status[0], "", {:class => "dropdown-item", "task_id" => task.id,  "onClick" => "changeStatus('#{task.id}','#{status[0]}')" })%>
          <% end %>
      </div>
      <% else %>
      <%= task.status%>
      <% end %>
    </td>
    <td scope="row">
      <div class="row px-3">
        <div class="col-4">
          <% if can? :show, task %>
            <%= link_to "", project_task_path(id: task) , class: "fa fa-eye text-primary" unless params.has_key?(:sprint_id)%>
            <%= link_to "", project_sprint_task_path(id: task) , class: "fa fa-eye text-primary" if params.has_key?(:sprint_id)%>
          <% end %>
        </div>
        <div class="col-4">
          <%if ((can? :edit, Task) && (['manager', 'admin'].include? current_user.roles.first.name)) %>
            <%=link_to "", edit_project_task_path(id: task) , class: "fa fa-edit text-success"%>
          <% end %>  
         </div>
         <div class="col-4">
          <% if can? :destroy, task %>
          <%= link_to "", 'javascript:;' , "onClick" => "deleteTask('#{task.sprint.project.id}','#{task.id}')"  , class: "fa fa-trash text-danger" %>
        </div>
      </div>
    </td>
    <% end%>
    <td scope="row">
      <div id="hours_<%=task.id%>"><%= @hours[task.id] %>
      </div>
    </td>
    
  </tr>
    
  <% end %>
    </tbody>

</table>
</div>
<script>
// ajax method for change project status 
// change no of hours

function changeStatus(id,drop_option) {
  select_id="#select_id_"+id;
  console.log(drop_option);
  $.ajax
  ({
    type: "patch",
    url: "/task/change_status",
    dataType: 'json',
    async: false,
    data: '{"id": "' + id + '", "status" : "' + drop_option + '"}',
    success: function (x){
      select_hours_id="#hours_"+id;
      $(select_hours_id).html(x["respons_message"])
      drop_button_id="#changeStatusDropDown_"+id;
     $(drop_button_id).html(drop_option)
      
 }
    
});
}

function deleteTask(project_id,id) {
    console.log(id,project_id);
    column_id="#column_"+id;
    url_str="/projects/"+project_id+"/task/"+id;
    if (confirm('Are you sure?')) {
      $.ajax
      ({
        type: "delete",
        url: url_str,
        async: false,
        data: '{form_where:"ajax"}',
    
        success: function (x){
          $(column_id).remove();
          console.log(x);
          $("#notice").html(x["respons_message"]);
        }
        
      });

    }
   
}

</script>

app/views/task/kanban.html.erb
<% status_class = {'Created'=> "info", 'On Going' => "primary", 'Submitted'=> "secondary", 'Re-Submitted' => "warning", 'Rejected'=>"danger", 'Done'=>"success"}%>
<div class="kanban d-flex flex-wrap">
  <% @status.each_with_index do |status,index|%>
    <% if index ==1%>
      <ul class="kanban-col col" id="on_going" data-id="<%=index%>">
      <% elsif index == 3 %>
        <ul class="kanban-col col" id="Re_Submitted" data-id="<%=index%>">
    <% else %>
      <ul class="kanban-col col" id="<%= status[0] %>" data-id="<%= index%>">
      <% end%>
        <li class="kanban-col-name py-2 bg-<%=status_class[status[0]]%>"><b><%= status[0] %></b></li>
        <% @tasks.where(status: status[0]).each do |task|%>
        <% next unless can? :edit, task%>
        <li class="kanban-col-item py-4" data-id="<%=task.id%>"><%= link_to task.title, project_task_path(project_id: task.sprint.project_id, id: task.id), class: "text-dark"%></li>
    <% end%>
      </ul>
  <% end%>
</div>
<script>
(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem('firstLoad') )
    {
      localStorage['firstLoad'] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem('firstLoad');
  }
})();
</script>

app/views/task/new.html.erb
<div class="container"  style="width: 30%; padding-top: 50px;" >
        <% if @task.errors.any? %>
        <div style="color: red">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
            <% @task.errors.each do |error| %>
            <li><%= error.full_message %></li>
                <% end %>
            </ul>
            </div>
        <% end %>
        <div class="col-md-12 pb-4">
            <h4>Create new Task</h4>
        </div>
    <%= render "form", task: @task, place: :create %>
        
  
         
</div>

      

app/views/task/show.html.erb
<div class="container">
<div>
  <% has_sprint_id = params.has_key?(:sprint_id)%>
  <%= link_to "Edit this Task", edit_project_task_path(id: @task)  ,:class => "btn btn-primary m-2" unless has_sprint_id%> 
  <%= link_to "Edit this Task", edit_project_sprint_task_path(id: @task)  ,:class => "btn btn-primary m-2" if has_sprint_id%>
  
  <%= link_to "Back to Tasks", project_task_index_path(@task.sprint.project) ,:class => "btn btn-primary m-2" unless has_sprint_id%> 
  <%= link_to "Back to Tasks", project_sprint_task_index_path(@task.sprint.project) ,:class => "btn btn-primary m-2" if has_sprint_id%> 
  
  <%= link_to "Destroy this Task", 'javascript:;' , "onClick" => "deleteTask('#{request.fullpath.to_s()}')" ,:class => "btn btn-primary m-2" ,class:"btn btn-danger text-white"if (can? :destroy, @task )%> 
    
   
</div>
<%= render "task", task: @task%>
<br>

<div class="card" style="width: auto;  border-radius: 25px;">
  <div class="card-body " style="background-color: #e0ffff; border-radius: 25px;">
<div class="p-2">
    <strong>Employee Name : </strong>
    <%= @task.user.name%>
</div>
<div class="p-2">
    <strong>Email : </strong>
    <%= @task.user.email%>
</div>
<div class="p-2">
    <strong>Due Data : </strong>
    <%= @task.due_date%>
</div>
<div class="p-2">
    <strong>Status : </strong>
    <%= @task.status%>
</div>
<br>
</div>
</div>
</div>
<script>

function deleteTask(s) {
    after_delete_url=s.split("/").slice(0,-1).join("/")
    
    url_str=s
    if (confirm('Are you sure?')) {
      $.ajax
      ({
        type: "delete",
        url: url_str,
        async: false,
        data: '{form_where:"ajax"}',
    
        success: function (x){
        
          window.location.href=after_delete_url;
        }
        
      });

    }
   
}
</script>