config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  default_url_options :host => ENV['HOST']
  devise_for :users, controllers: { 
    registrations: 'users/registrations', 
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  patch 'task/change_status', action: :change_status, controller: 'task'
  get 'schedule', to: 'schedule#index'
  get 'kanban', to: 'task#kanban'

  # patch "task/change_status" , to:"tasks#change_status"
  
  resources :role
  resources :users do
    collection do
      post 'create_user'
      patch 'change_image'
    end
  end

  resources :issues do 
    collection do 
      get 'assign_issue_show'
      patch 'assign_issue'
      get 'my_issue'
    end
  end
  resources :tags   do 
     
  end
  resources :projects do

    resources :sprint do
      resources :task do
        collection do 
          get "kanban"
        end
      end
      collection do
        
      end
    end
    
    resources :task do
      collection do 
        get "kanban"
      end
    end
    collection do

      patch "save_review_rating"
      get "project_status"
      get "review_rating"
     
    end
  end

  
  resources :admin do
    collection do
      get 'soft_delete'
      get "alluser"
    end
  end
 
  root "home#index"
  get 'employee', to: 'home#employee'
  
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  acts_as_paranoid
  belongs_to :creator, class_name: 'User'
  belongs_to :client, class_name: 'User'
  has_many :sprints, class_name: 'Sprint', dependent: :destroy
  
  has_many :taggings, as: :taggable, dependent: :destroy

  has_many :tags ,through: "taggings", dependent: :destroy
  filterrific(
    default_filter_params: { sorted_by: 'name_asc' },
    available_filters: [
      :sorted_by,
      :search_query,
      :with_status
    ]
  )

  scope :search_query, ->(query) {
    return nil  if query.blank?
    Project.where('lower(projects.description) LIKE :search OR lower(projects.name) LIKE :search', search: "%#{query.downcase}%")
  }

  scope :with_status, ->(status) {
    if(status == "overdue")
      where("endingdate < '#{Time.now}' and status!='completed'")
    else
      where(:status => [status])
    end
  }

  scope :sorted_by, ->(sort_option) {
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    projects = Project.arel_table
    tasks = Task.arel_table
    case sort_option.to_s
    when /^name_/
      order(projects[:name].lower.send(direction))
    when /^created_at_/
      order(projects[:created_at].send(direction))
    when /^endingdate/
      order(projects[:endingdate].send(direction))
    when /^updated_at/
      order(projects[:updated_at].send('desc'))
    when /^task/
      Project.joins(sprints: :tasks).group("projects.id").order('COUNT(project_id) asc')
      # Project.where(id:ids)
    else
      raise(ArgumentError, "Invalid sort option: #{sort_option.inspect}")
    end
  }

  def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Project start date', 'created_at_asc'],
      ['Project End date', 'endingdate'],
      ['Last Modified', 'updated_at'],
      ['Tasks', 'task']
    ]
  end

  def self.options_for_with_status
    [
      ['Completed', 'completed'],
      ['On Going', 'ongoing'],
      ['Over Due', 'overdue']
    ]
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_project_by_format, only: %i[project_status]
  before_action :checking_authenticity_update, only: %i[edit update destroy]
  before_action :checking_authenticity_show, only: %i[show]
  before_action :checking_authenticity_status, only: %i[project_status]
  before_action :checking_authenticity_new, only: %i[new create]
  # GET /projects or /projects.json
  def index
    # if current_user.has_role? 'employee'
    #   arr = Task.select(:sprint_id).where(user_id: current_user.id).map(&:sprint_id).uniq
    #   @projects = Project.joins(:sprints).where(sprints: { id: arr })
    #   return @projects
    # end
    # @projects = Project.all


    @filterrific = initialize_filterrific(
      Project,
      params[:filterrific],
      select_options: {
        sorted_by: Project.options_for_sorted_by,
        with_status: Project.options_for_with_status,
      },
      persistence_id: "shared_key",
      default_filter_params: {},
      available_filters: [:sorted_by, :with_status, :search_query],
      sanitize_params: true,
    ) || return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOTE: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    if current_user.has_role? 'employee'
      arr = Task.select(:sprint_id).where(user_id: current_user.id).map(&:sprint_id).uniq
      @projects = @filterrific.find.page(params[:page]).joins(:sprints).where(sprints: { id: arr }).paginate(page: params[:page], per_page: 9)
      # return @projects
    else 
      @projects = @filterrific.find.page(params[:page]).paginate(page: params[:page], per_page: 9)
    end
    # @projects = Project.all

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    # project_id = params[:id]
    # @sprint = Sprint.where(project_id: project_id).all
    # @completed = Project.find(project_id).sprints.joins(:tasks).where(tasks: { status: 'Done' }).count
    # @ongoing = Project.find(project_id).sprints.joins(:tasks).count - @completed

    @filterrific = initialize_filterrific(
      Sprint,
      params[:filterrific],
      select_options: {
        sprint_sorted_by: Sprint.options_for_sorted_by,
        with_sprint_status: Sprint.options_for_with_status,
      },
      persistence_id: "shared_key",
      default_filter_params: {},
      available_filters: [:sprint_sorted_by, :sprint_search_query, :with_sprint_status],
      sanitize_params: true,
    ) || return

    project_id = params[:id]
    @sprint = @filterrific.find.page(params[:page]).where(project_id: project_id).paginate(page: params[:page], per_page: 9)
    @completed = Project.find(project_id).sprints.joins(:tasks).where(tasks: { status: 'Done' }).count
    @ongoing = Project.find(project_id).sprints.joins(:tasks).count - @completed
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @client = []
    @manager = []
    @project_tag=Tag.where(tag_type:"Project")
    User.joins(:roles).where(roles: { name: 'customer' }).select(:id, :name).each { |v| @client << [v.name, v.id] }
    @project = Project.new
    if current_user.roles.first.name == 'admin'
      User.joins(:roles).where(roles: { name: 'manager' }).select(:id, :name).each { |v| @manager << [v.name, v.id] }
    else
      @manager << current_user.id
    end
  end

  def edit

    @project_tag=Tag.where(tag_type:"Project")
    
    
    @project = Project.find(params[:id])
    @project_tag_selected=[]
    @project.tags.select("id").each do |x|
      @project_tag_selected.<<x.id
    end
    params[:selected_value] = @project.client_id
    params[:selected_manager] = @project.creator_id
    params[:tages]=@project.tags
    @client = []
    @manager = []
    User.joins(:roles).where(roles: { name: 'customer' }).select(:id, :name).each { |v| @client << [v.name, v.id] }
    if current_user.roles.first.name == 'admin'
      User.joins(:roles).where(roles: { name: 'manager' }).select(:id, :name).each { |v| @manager << [v.name, v.id] }
    else
      @manager << current_user.id
    end
  end

  def create
    @project = Project.new(project_params)
    @project.status = 'ongoing'
    tage = params.require(:tages)
    # raise "a"
    params[:selected_value] = @project.client_id
    tage.each do |x|
      @project.tags<<Tag.find(x)
    end
    respond_to do |format|
      if @project.save
        
        ProjectMailer.with(project: @project).project_created.deliver_later
        format.html { redirect_to project_url(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    tage = params.require(:tages)
    @project.tags.clear()
    tage.each do |x|
      @project.tags<<Tag.find(x)
    end
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def review_rating
    @project = Project.find(params[:format])
  end

  def save_review_rating
    @project = Project.find(params[:project][:id])
    respond_to do |format|
      if @project.update(project_params_review)
        format.html { redirect_to project_url(@project), notice: 'Thank You for Rating' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    render json: { respons_message: 'Project was successfully destroyed.' }
  end

  def project_status
    @project = Project.find(params[:format])
    @project.status = params[:status] == 'true' ? 'completed' : 'ongoing'
    redirect_to action: 'show', id: @project if @project.save
  end

  private

  def set_project
    @project = Project.find_by(id: params[:id])
    redirect_to projects_path if @project.nil?
  end

  def set_project_by_format
    @project = Project.find(params[:format])
  end

  def project_params
    params.require(:project).permit(:name, :description, :client_id, :endingdate, :creator_id)
  end

  def checking_authenticity_show
    render file: 'public/403.html' unless can? :show, @project
  end

  def checking_authenticity_update
    render file: 'public/403.html' unless can? :update, @project
  end

  def checking_authenticity_status
    render file: 'public/403.html' unless can? :project_status, @project
  end

  def checking_authenticity_new
    render file: 'public/403.html' unless can? :new, Project
  end

  def project_params_review
    params.require(:project).permit(:reviews, :rating)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    
    def getAlertLabel(day_left, isCompleted)
        if isCompleted
            "<div class='label  badge badge-success rounded'>Completed</div>"
        elsif day_left < 8 && day_left > 0
            "<div class='label bg-info rounded text-white'>day left <span class='lable badge badge-danger rounded-circle mb-1'>#{day_left.to_i}</span></div>"
        elsif day_left == 0
            "<div class='label bg-danger rounded text-white'>Need to Complete Today</div>"
        elsif day_left < 0
            "<div class='label bg-info rounded text-white'>Overdue by <span class='lable badge badge-danger rounded-circle mb-1'>#{day_left.to_i.abs}</span> days</div>"
        end
    end
end

app/views/projects/_form.html.erb
<%= stylesheet_link_tag "select2_scss", :media => "all" %>
    
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-12">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-12">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-12">
      <%= form.label "Expected Ending date", class: "form-label" %>
      <%= form.date_select :endingdate, class: "form-control" %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-12">
      <%= form.label :client, class: "form-label" %>
      <%= form.select :client_id , @client, selected: params[:selected_value] %>
    </div>
  </div>

  <% if current_user.has_role?(:admin) %>
    <div class="row mt-2">
      <div class="col-12">
        <%= form.label :manager %>
        <%= form.select :creator_id , @manager, :selected => params[:selected_manager] %>
      </div>
    </div>
    <span class="dot"></span>
    <select class="js-example-basic-multiple form-control" name="tages[]" multiple="multiple" id="tag_id">
      <%@project_tag.each do |x|%>
        <option value="<%=x.id%>" color="<%=x.color%>"><%=x.tag_name%></option>
      <%end%>
  </select>
  <% else %>
    <%= form.hidden_field  :creator_id, value:current_user.id%>
  <% end %>

  <div class="row mt-3 justify-content-end">
    <%= form.submit class: 'btn btn-success mr-2' %>
    <%= link_to 'Back', projects_path, class: 'btn btn-info mr-2' %>
  </div>
<% end %>
<div data-controller="select2" data-selectedTag='<%=@project_tag_selected%>'>
</div>
<script>
</script>

app/views/projects/_project.html.erb
<style>
.card .label {
  position: absolute;
    right: 6px;
    top: -5px;
}
</style>
<div class="row project-row">
      <% projects.each do |project| %>
        <%
          unless current_user.has_role? "employee"
            next unless  can? :show, project
          end %>

<%
  task_percentage = 0
  completed = project.sprints.joins(:tasks).select("tasks.id").where("tasks.status = 'Done'").count
  total = project.sprints.joins(:tasks).select("tasks.*").count
  task_percentage = (completed.to_f/total)*100 unless total == 0
  day_left = project.endingdate - Date.today
%>

  <div class="col-sm-9 col-lg-6 col-xl-4 card-sorting" id="<%= dom_id project %>">
    <div class="card card-wrapper" style="margin-bottom:20px">
      <div class="card-body">
        <h4 class="card-title h2"><%= project.name %></h4>
        <p class="card-text text-muted description" data-toggle="tooltip" data-placement="bottom" title="<%=project.description%>"><%=project.description%></p>
        <p class='card-text text-info'>Total Task: <%= total%>
         <p class='card-text text-success'>Start Date: <%= project.created_at.to_date%>
         <p class='card-text text-danger'>End Date: <%= project.endingdate%>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: <%=task_percentage%>%" aria-valuenow="<%= task_percentage%>%" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

        <%=sanitize getAlertLabel(day_left, project.status == "completed")%>
      </div>
      <div class="card-footer bg-white">
        <div class="row">
            <div class="col-12">
              <%= link_to 'View', project,  class: "badge badge-info p-2 mt-1 text-white" %>
              <%= link_to 'Edit', edit_project_path(project),  class: 'badge badge-warning p-2 mt-1 text-white' if can? :update, project %>
              <%= link_to "Delete", 'javascript:;',class:"badge badge-danger p-2 mt-1 text-white" , "onClick" => "deleteProject('#{project.id}')" if can? :destroy, project  %>
            </div>
          </div>
        </div>
    </div>
  </div>
    <% end%>
<script>
  function deleteProject(id) {
    console.log(id);
    column_id="#project_"+id;
    url_str="/projects/"+id;
    // projects/:project_id/sprint/:id
    if (confirm('Are you sure?')) {
      $.ajax
      ({
        type: "delete",
        url: url_str,
        async: false,
        success: function (x){
          $(column_id).remove();
          console.log(x);
          $("#notice").html(x["respons_message"]);
        }
        
      });

    }
   
}

</script>

app/views/projects/_sprint.html.erb
<style>
.card .label {
  position: absolute;
    right: 6px;
    top: -5px;
}
</style>

<% sprints.each do |sprint| %>
  <% project = sprint.project%>
  <%  task_percentage = 0
      completed = sprint.tasks.where("tasks.status = 'Done'").count
      total = sprint.tasks.count
      task_percentage = (completed.to_f/total)*100 unless total == 0
      day_left = sprint.expected_end_date - Date.today
  %>

  <div class="col-sm-12 col-lg-6 col-xl-4 my-1" id="<%=dom_id sprint%>">
    <div class="card card-wrapper">
      <div class="card-body">
        <h4 class="card-title h2"><%= sprint.title %></h4>
        <small>Start At: <%= sprint.created_at.strftime('%d-%m-%y') %></small><br>
        <small>Expected End At: <%= sprint.expected_end_date&.strftime('%d-%m-%y') %></small><br>
        <p class="card-text text-muted description" data-toggle="tooltip" data-placement="bottom" title="<%=sprint.description%>"><%=sprint.description%></p>
        <p class='card-text text-info'>Total Task: <%= total%></p>
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: <%=task_percentage%>%" aria-valuenow="<%= task_percentage%>%" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
        <%=sanitize getAlertLabel(day_left, total==completed)%>
    <div class="row d-table-row">
        <div class="col-12 card-footer bg-white">
            <%= link_to "View Task", project_sprint_task_index_path(project, sprint), class:"badge badge-success p-1"%>
            <%= link_to "Edit Sprint", edit_project_sprint_path(project_id: project,id:sprint), class:"badge badge-primary p-1" if can? :update, @project%>
            <%= link_to "Delete", 'javascript:;',class:"badge badge-danger p-1" , "onClick" => "deleteSprint('#{project.id}','#{sprint.id}')" if can? :destroy, @project  %>
        </div>
      </div>
  </div>
</div>

<% end %>
<script>
  function deleteSprint(project_id,id) {
    console.log(id,project_id);
    column_id="#sprint_"+id;
    url_str="/projects/"+project_id+"/sprint/"+id;
    // projects/:project_id/sprint/:id
    if (confirm('Are you sure?')) {
      $.ajax
      ({
        type: "delete",
        url: url_str,
        async: false,
        success: function (x){
          $(column_id).remove();
          console.log(x);
          $("#notice").html(x["respons_message"]);
        }
        
      });

    }
   
}

</script>

app/views/projects/edit.html.erb
<h1>Editing project</h1>
<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

<div class="row">
  <div class="col-3">
    <h1>Projects</h1>
  </div>
  <div class="col-9 d-flex align-items-center">
    <div>
        <%= link_to 'New project', new_project_path, class: 'btn btn-outline-primary' if can? :create, Project %>
    </div>
  <%= form_for_filterrific @filterrific, html: { id: '', class:"form-inline ml-4" } do |f| %>
  <div class= "d-flex align-items-center justify-content-around">
      <div>
        <%= f.text_field(
          :search_query,
          class: 'filterrific-periodically-observed form-control',
          placeholder: "Search"
        ) %>
   
      <%= f.select(
        :with_status, 
        @filterrific.select_options[:with_status],
        { include_blank: '- Status -'},
        {class:"form-control"}
      ) %>
   
      <%= f.select(
        :sorted_by, 
        @filterrific.select_options[:sorted_by], 
        { include_blank: '- Sorted By -' },
        {class:"form-control"}
        ) %>
      <%= f.submit 'Filter', class: "btn btn-primary" %>
      <%= link_to(
        'Reset filters',
        reset_filterrific_url,
        :class=>"btn btn-secondary"
      ) %>
   </div>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%# render_filterrific_spinner %>
<% end %>

  </div>
  </div>

<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-3">
    <canvas id="myChart" ></canvas>
  </div>
  <div class="col-sm-12 col-md-6 col-lg-9 filterrific_results">
     <%= render(
          partial: 'projects/project',
          locals: { projects: @projects }
        ) %>
  </div>
</div>
<% completed = Project.where(status: "completed").count
  if @projects.count.is_a?(Hash)
    count=0
    @projects.count.each do |k,v|
      count = count + v.to_i
    end
  else
    count = @projects.count
  end
  on_going = count - completed %>

<% if count > 9%>
<div class="col-12">
   <div class="apple_pagination">
    <%= will_paginate @projects, :container => false %>
  </div>
</div>
<% end %>


<script>
  var xValues = ["In Progess", "Completed"];
  var yValues = [<%=on_going%>, <%= completed%>];
  var barColors = ["#b91d47", "#00aba9"];

  new Chart("myChart", {
    type: "pie",
    data: {
      labels: xValues,
      datasets: [{
        backgroundColor: barColors,
        data: yValues
      }]
    },
    options: {
      title: {
        display: true,
        text: "All Projects Status"
      }
    }
  });

</script>

app/views/projects/index.js.erb
<% js = escape_javascript(
  render(
    :partial => 'projects/project',
    :locals => { :projects => @projects }
  )
) %>
$("#filterrific_results").html("<%= js %>");

app/views/projects/new.html.erb
<div class = "container mt-5">
  <h2 class="head-text mt-6">New project</h2>
  <%= render "form", project: @project %>
</div>

app/views/projects/review_rating.html.erb
<%= form_with model: @project,url: save_review_rating_projects_path do |form| %>
   
        <%= form.hidden_field :id %> 
    <div>
        <%= form.label :reviews, style: "display: block" %>
        <%= form.text_area :reviews %>
  </div>
 <div>
        <%= form.label :rating, style: "display: block" %>
       <%= form.select :rating ,(1..10).each %>
  </div>
   <div>
    <%= form.submit value="Save Project"%>
  </div>

<%end%>

app/views/projects/show.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>

<div class="row">
  <div class="col-12 text-right">
    <%= link_to "Kanban", kanban_project_task_index_path(@project),class:"btn btn-outline-primary" unless current_user.has_role? "customer"%>
    <%= link_to "Tasks", project_task_index_path(@project),class:"btn btn-outline-dark"%>
    <%= link_to "My Assigned issues", my_issue_issues_path(@project),class:"btn btn-outline-secondary" %>
    <%= link_to "Create Sprint", new_project_sprint_path(@project), class: "btn btn-outline-success mr-1" if can? :create, @project %>
    <%= link_to "Create issue", new_issue_path(@project), class: "btn btn-outline-danger mr-1" if can? :create, @project %>
    <%= link_to "Show issues", issues_path(@project), class: "btn btn-outline-warning mr-1" %>
    <%= link_to "Back", projects_path, class: "btn btn-outline-info mr-3" %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12 col-xl-4">
    <div class="col-12 mt-5"><h4><%= @project.name %></h4></div>
    <div class="col-12 mt-3 text-muted"><%= @project.description %></div>
    <div class="col-12 mt-3"><b>Status: </b><%= @project.status %></div>
    <div class="col-12 mt-3">
    <%@project.tags.each do |x|%>
    
      <span class="rectangle" style="background:<%=x.color%>;color:<%=get_font_color(x.color)%>"><%=x.tag_name%></span>
    <%end%>
    </div>
    <% if can? :project_status, @project %>
      <div class="col-12 mt-3">
        <b>Change to: </b>
        <% if @project.status=="completed" &&(can? :project_status, @project) %>
          <%= link_to "Ongoing", project_status_projects_path(@project,status: false) if can? :project_status, @project %>
        <% else %>
          <%= link_to "Completed", project_status_projects_path(@project,status: true),class:"text-success" if can? :project_status, @project %>
        <% end %>
      </div>
    <% end %>
    <div class="col-12">
      <% if @project.status=="completed" && @project.client_id==current_user.id %>
      <%= link_to "Review And Rating", review_rating_projects_path(@project) if can? :review_rating, @project %>
      <% end %>
    </div>
    <div  class="col-12 mt-3">
      <canvas id="myChart" style="width:50%;max-width:600px"></canvas>  
    </div>
  </div>
  <div class="col-lg-12 col-xl-8">
    <div class="row">
      <div class="col-12">
        <h2>All Sprints</h2>
      </div>
    </div>
    <div class="row">
      <%= form_for_filterrific @filterrific, html: { id: 'filterrific-no-ajax-auto-submit', class:"form-inline ml-4" } do |f| %>
        <div class= "d-flex align-items-center justify-content-around">
            <div>
              <%= f.text_field(
                :sprint_search_query,
                class: 'filterrific-periodically-observed form-control',
                placeholder: "Search"
              ) %>
              <%= f.select(
                :with_sprint_status, 
                @filterrific.select_options[:with_sprint_status],
                { include_blank: '- Status -'},
                {class:"form-control"}
              ) %>
              <%= f.select(
                :sprint_sorted_by, 
                @filterrific.select_options[:sprint_sorted_by], 
                { include_blank: '- Sorted By -' },
                {class:"form-control"}
                ) %>
              <%= f.submit 'Filter', class: "btn btn-primary" %>
              <%= link_to(
                'Reset filters',
                reset_filterrific_url,
                :class=>"btn btn-secondary"
              ) %>
          </div>
        </div>
        <%# add an automated spinner to your form when the list is refreshed %>
        <%# render_filterrific_spinner %>
      <% end %> 
    </div>
    <div class="row filterrific_results_sprint" >
          <%=
          render(
            :partial => 'projects/sprint',
            :locals => { :sprints => @sprint }
          )
          %>
    </div>
    <% if (@ongoing + @completed) > 9%>
      <div class="col-12">
        <div class="apple_pagination">
          <%= will_paginate @sprint, :container => false %>
        </div>
      </div>
      <% end %>
  </div>
</div>

<script>
var xValues = ["In Progess", "Completed"];
var yValues = [<%=@ongoing%>, <%= @completed%>];
var barColors = [
  "#b91d47",
  "#00aba9"
];

new Chart("myChart", {
  type: "pie",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    title: {
      display: true,
      text: "All Task Status"
    }
  }
});
</script>

app/views/projects/show.js.erb
<% js = escape_javascript(
  render(
    :partial => 'projects/sprint',
    :locals => { :sprints => @sprint }
  )
) %>
$(".filterrific_results_sprint").html("<%= js %>");