config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :users
  default_url_options :host => ENV['HOST']
  devise_for :users, controllers: { 
    registrations: 'users/registrations', 
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  patch 'task/change_status', action: :change_status, controller: 'task'
  get 'schedule', to: 'schedule#index'
  get 'kanban', to: 'task#kanban'

  # patch "task/change_status" , to:"tasks#change_status"
  
  resources :role
  resources :users do
    collection do
      post 'create_user'
      patch 'change_image'
    end
  end

  resources :issues do 
    collection do 
      get 'assign_issue_show'
      patch 'assign_issue'
      get 'my_issue'
    end
  end
  resources :tags   do 
     
  end
  resources :projects do

    resources :sprint do
      resources :task do
        collection do 
          get "kanban"
        end
      end
      collection do
        
      end
    end
    
    resources :task do
      collection do 
        get "kanban"
      end
    end
    collection do

      patch "save_review_rating"
      get "project_status"
      get "review_rating"
     
    end
  end

  
  resources :admin do
    collection do
      get 'soft_delete'
      get "alluser"
    end
  end
 
  root "home#index"
  get 'employee', to: 'home#employee'
  
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings, dependent: :destroy

    has_many :projects, through: :taggings, source: :taggable, source_type: 'Project', dependent: :destroy
    has_many :tasks, through: :taggings, source: :taggable, source_type: 'Task', dependent: :destroy
    has_many :sprints, through: :taggings, source: :taggable, source_type: 'Sprints', dependent: :destroy
    has_many :issues, through: :taggings, source: :taggable, source_type: 'Issues', dependent: :destroy

    validates :tag_name, presence: :true
    enum type_of_lable: { Project: "Project", Task:"Task",
        Sprint:"Sprint",Issue:"Issue"}
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :set_tag, only: %i[ show edit update destroy ]

    def index
        @tags=Tag.all
    end
    def new 
        @tag=Tag.new
    end
    
    def create
        @tag = Tag.new(tag_params)
        respond_to do |format|
            if @tag.save
                add_flash_message('notice', "Tag was successfully created.")
                format.html { redirect_to tag_url(@tag) }
              format.json { render :show, status: :created, location: @tag }
            else
                
                @tag.errors.each do |error|
                    add_flash_message('error',  error.full_message)
                end
  
              format.html { redirect_to new_tag_url, status: :unprocessable_entity }
             end
        end
    end
    def edit
    end
    def update
        f=0
    respond_to do |format|
      if @tag.update(tag_params)
        if(f==1)
            @tag.where(tag_type: tag_params[:tag_type])
        end
        add_flash_message('notice', "Book was successfully updated.")
        format.html { redirect_to tag_url(@tag) }
        format.json { render :show, status: :ok, location: @book }
      else

        @tag.errors.each do |error|
            add_flash_message('error',  error.full_message)
        end
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
        p "-----------"
    end
    
    private 
    def set_tag
        @tag=Tag.find_by(id:params[:id])
    end
    def tag_params
        params.require(:tag).permit(:tag_name, :tag_type,:color)
    end
end

app/helpers/tag_helper.rb
module TagHelper
    def get_font_color(background)
        return "white" if(background.paint.dark? )
        return "balck" 
        
    end
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  
  <div>
    <%= form.label :tag_name, style: "display: block" %>
    <%= form.text_field :tag_name %>
  </div>
  <div>
    <%= form.label :tag_type, style: "display: block" %>
    <%= form.select :tag_type,Tag.type_of_lables %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.color_field :color %>
  </div>
</div>

  <div>
    <%= form.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
<%=link_to "Show",tag_path(id:@tag) %><br>
    
<%=link_to "back to Tags ", tags_path %><br>

</div>

app/views/tags/index.html.erb
<%@tags.each do |x|%>
    <%=x.tag_name%>---------<%=x.tag_type%> 
<%=link_to "Show",tag_path(id:x) %><br>
    
<%end%>
<%=link_to "New Tag",new_tag_path %><br>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render "form", tag: @tag %>

<br>

app/views/tags/show.html.erb
tag_type<%=@tag.tag_type%><br>
tag_name<%=@tag.tag_name%><br>
color <%=@tag.color%><br>

<%=link_to "back to Tags ", tags_path %><br>

<%=link_to "Edit Tag ", edit_tag_path %><br>